### ISSUE TITLE
Some users cannot log in

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#495]
Very difficult to track as it happens to very few users, but some users get an error Match Failed when trying to login. 
On the server, it says, when using v1.3.5:
```
 Exception while invoking method 'login' Error: Match error: Match error: Failed Match.Where validation in field username in field user.username
   at check (packages/check/match.js:35:15)
   at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:266:3)
   at packages/accounts-base/accounts_server.js:483:32
   at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
   at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:480:18)
   at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:543:27)
   at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
   at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
   at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
   at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
   at Promise (packages/ddp-server/livedata_server.js:715:46)
   at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
 Sanitized and reported to the client as: Match failed [400]
```

An update to LoginBox to change the call the Meteor.loginWithPassword() from using this.state.email. to {email:this.state.email}, still gives the error, but then it complains about field email in user.email:
```
 Exception while invoking method 'login' Error: Match error: Match error: Failed Match.Where validation in field email in field user.email
     at check (packages/check/match.js:35:15)
     at MethodInvocation.<anonymous> (packages/accounts-password/password_server.js:266:3)
     at packages/accounts-base/accounts_server.js:483:32
     at tryLoginMethod (packages/accounts-base/accounts_server.js:259:14)
     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:480:18)
     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:543:27)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
     at Promise (packages/ddp-server/livedata_server.js:715:46)
     at new Promise (<anonymous>)
     at Session.method (packages/ddp-server/livedata_server.js:689:23)
     at packages/ddp-server/livedata_server.js:559:43
 Sanitized and reported to the client as: Match failed [400]

```

Not clear when this starting happening; one student mentionned that this was recent, but reverting to v1.3.5 did not fix things (observed for sure in v.1.3.5, v1.3.5 and v1.3.7)

**Comment by ryanmartinneutrino** [comment]
Maybe fixed by PR #498 (maybe the commit that requires that this.state.email and this.state.password are not null in LoginBox)?
