### ISSUE TITLE
Verification email cannot be resend by admin.

### ISSUE THREAD

**Issue by zjevik** [qlicker/qlicker#551]
If admin opens an unverified profile and clicks on the "Send Verification Email" button not email is sent and the following error is recorded:

> Exception while invoking method 'users.sendVerificationEmailTo' TypeError: Meteor.user.hasGreaterRole is not a function
    at MethodInvocation.users.sendVerificationEmailTo (imports/api/users.js:190:50)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43

**Comment by ryanmartinneutrino** [comment]
Should be fixed by PR #552, updated on docker, qlicker/qlicker:v1.4.2.
Thanks for pointing this out!
